"""Authoritative manifest-aware validator with machine-readable reporting."""
from pathlib import Path
import json
import subprocess
import sys
from datetime import datetime, timezone
ROOT=Path(__file__).resolve().parents[1]
REPORT_DIR=ROOT/'reports'; REPORT_DIR.mkdir(exist_ok=True)
CHECKS=['validate_manifest.py','validate_schema_files.py','validate_yaml.py','validate_references.py','validate_continuity.py','validate_graph.py','validate_final_state.py']
def main():
    results=[]
    for name in CHECKS:
        path=ROOT/'tools'/name
        if not path.exists(): results.append({'name':name,'status':'MISSING','returncode':None,'output':''}); continue
        result=subprocess.run([sys.executable,str(path)],cwd=ROOT,capture_output=True,text=True)
        results.append({'name':name,'status':'PASS' if result.returncode==0 else 'FAIL','returncode':result.returncode,'output':(result.stdout+result.stderr).strip()})
    report={'generated_at_utc':datetime.now(timezone.utc).isoformat(),'repository':'xabiervc/breaking-chains-rome','checks':results,'overall':'PASS' if all(item['status']=='PASS' for item in results) else 'FAIL','execution_note':'Generated by local or CI execution; source-control writes alone do not constitute execution.'}
    (REPORT_DIR/'validation-report.json').write_text(json.dumps(report,indent=2),encoding='utf-8')
    lines=['# Validation Report','',f"Generated: {report['generated_at_utc']}",f"Overall: **{report['overall']}**",'', '## Checks']
    for item in results: lines.append(f"- `{item['name']}`: **{item['status']}**" + (f" — {item['output']}" if item['output'] else ''))
    (REPORT_DIR/'validation-report.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')
    print(json.dumps(report,indent=2))
    return 0 if report['overall']=='PASS' else 1
if __name__=='__main__': sys.exit(main())
